/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as MutuelleSanteRouteImport } from './routes/mutuelle-sante'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AssuranceObsequesRouteImport } from './routes/assurance-obseques'
import { Route as AssuranceEmprunteurRouteImport } from './routes/assurance-emprunteur'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiLeadRouteImport } from './routes/api/lead'

const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MutuelleSanteRoute = MutuelleSanteRouteImport.update({
  id: '/mutuelle-sante',
  path: '/mutuelle-sante',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceObsequesRoute = AssuranceObsequesRouteImport.update({
  id: '/assurance-obseques',
  path: '/assurance-obseques',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceEmprunteurRoute = AssuranceEmprunteurRouteImport.update({
  id: '/assurance-emprunteur',
  path: '/assurance-emprunteur',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assurance-emprunteur': typeof AssuranceEmprunteurRoute
  '/assurance-obseques': typeof AssuranceObsequesRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgu': typeof CguRoute
  '/leads': typeof LeadsRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mutuelle-sante': typeof MutuelleSanteRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visitors': typeof VisitorsRoute
  '/api/lead': typeof ApiLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assurance-emprunteur': typeof AssuranceEmprunteurRoute
  '/assurance-obseques': typeof AssuranceObsequesRoute
  '/cgu': typeof CguRoute
  '/leads': typeof LeadsRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mutuelle-sante': typeof MutuelleSanteRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visitors': typeof VisitorsRoute
  '/api/lead': typeof ApiLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assurance-emprunteur': typeof AssuranceEmprunteurRoute
  '/assurance-obseques': typeof AssuranceObsequesRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgu': typeof CguRoute
  '/leads': typeof LeadsRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mutuelle-sante': typeof MutuelleSanteRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visitors': typeof VisitorsRoute
  '/api/lead': typeof ApiLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assurance-emprunteur'
    | '/assurance-obseques'
    | '/blog'
    | '/cgu'
    | '/leads'
    | '/mentions-legales'
    | '/mutuelle-sante'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/visitors'
    | '/api/lead'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assurance-emprunteur'
    | '/assurance-obseques'
    | '/cgu'
    | '/leads'
    | '/mentions-legales'
    | '/mutuelle-sante'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/visitors'
    | '/api/lead'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/assurance-emprunteur'
    | '/assurance-obseques'
    | '/blog'
    | '/cgu'
    | '/leads'
    | '/mentions-legales'
    | '/mutuelle-sante'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/visitors'
    | '/api/lead'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssuranceEmprunteurRoute: typeof AssuranceEmprunteurRoute
  AssuranceObsequesRoute: typeof AssuranceObsequesRoute
  BlogRoute: typeof BlogRouteWithChildren
  CguRoute: typeof CguRoute
  LeadsRoute: typeof LeadsRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MutuelleSanteRoute: typeof MutuelleSanteRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisitorsRoute: typeof VisitorsRoute
  ApiLeadRoute: typeof ApiLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante': {
      id: '/mutuelle-sante'
      path: '/mutuelle-sante'
      fullPath: '/mutuelle-sante'
      preLoaderRoute: typeof MutuelleSanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-obseques': {
      id: '/assurance-obseques'
      path: '/assurance-obseques'
      fullPath: '/assurance-obseques'
      preLoaderRoute: typeof AssuranceObsequesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-emprunteur': {
      id: '/assurance-emprunteur'
      path: '/assurance-emprunteur'
      fullPath: '/assurance-emprunteur'
      preLoaderRoute: typeof AssuranceEmprunteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssuranceEmprunteurRoute: AssuranceEmprunteurRoute,
  AssuranceObsequesRoute: AssuranceObsequesRoute,
  BlogRoute: BlogRouteWithChildren,
  CguRoute: CguRoute,
  LeadsRoute: LeadsRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MutuelleSanteRoute: MutuelleSanteRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisitorsRoute: VisitorsRoute,
  ApiLeadRoute: ApiLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
