/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as TarifMutuelleSanteRouteImport } from './routes/tarif-mutuelle-sante'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrixMutuelleSanteRouteImport } from './routes/prix-mutuelle-sante'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as MutuelleSeniorPasCherRouteImport } from './routes/mutuelle-senior-pas-cher'
import { Route as MutuelleSenior70AnsRouteImport } from './routes/mutuelle-senior-70-ans'
import { Route as MutuelleSanteToulouseRouteImport } from './routes/mutuelle-sante-toulouse'
import { Route as MutuelleSanteSansDelaiCarenceRouteImport } from './routes/mutuelle-sante-sans-delai-carence'
import { Route as MutuelleSantePasChereRouteImport } from './routes/mutuelle-sante-pas-chere'
import { Route as MutuelleSanteParisRouteImport } from './routes/mutuelle-sante-paris'
import { Route as MutuelleSanteMarseilleRouteImport } from './routes/mutuelle-sante-marseille'
import { Route as MutuelleSanteLyonRouteImport } from './routes/mutuelle-sante-lyon'
import { Route as MutuelleSanteIndependantRouteImport } from './routes/mutuelle-sante-independant'
import { Route as MutuelleSanteFonctionnaireRouteImport } from './routes/mutuelle-sante-fonctionnaire'
import { Route as MutuelleSanteFamilleRouteImport } from './routes/mutuelle-sante-famille'
import { Route as MutuelleSanteExpatrieRouteImport } from './routes/mutuelle-sante-expatrie'
import { Route as MutuelleSanteEtudiantRouteImport } from './routes/mutuelle-sante-etudiant'
import { Route as MutuelleSanteEntrepriseRouteImport } from './routes/mutuelle-sante-entreprise'
import { Route as MutuelleSanteEnLigneRouteImport } from './routes/mutuelle-sante-en-ligne'
import { Route as MutuelleSanteBordeauxRouteImport } from './routes/mutuelle-sante-bordeaux'
import { Route as MutuelleSanteRouteImport } from './routes/mutuelle-sante'
import { Route as MutuelleOptiqueRouteImport } from './routes/mutuelle-optique'
import { Route as MutuelleDentaireRouteImport } from './routes/mutuelle-dentaire'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MeilleureMutuelleSanteRouteImport } from './routes/meilleure-mutuelle-sante'
import { Route as LoiLemoineRouteImport } from './routes/loi-lemoine'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DevisMutuelleSanteRouteImport } from './routes/devis-mutuelle-sante'
import { Route as ContratObsequesRouteImport } from './routes/contrat-obseques'
import { Route as ComplementaireSanteRouteImport } from './routes/complementaire-sante'
import { Route as ComparateurMutuelleSeniorRouteImport } from './routes/comparateur-mutuelle-senior'
import { Route as ComparateurMutuelleSanteRouteImport } from './routes/comparateur-mutuelle-sante'
import { Route as ChangerAssuranceEmprunteurRouteImport } from './routes/changer-assurance-emprunteur'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AssuranceObsequesRouteImport } from './routes/assurance-obseques'
import { Route as AssuranceHospitalisationRouteImport } from './routes/assurance-hospitalisation'
import { Route as AssuranceEmprunteurRouteImport } from './routes/assurance-emprunteur'
import { Route as AssuranceDecesRouteImport } from './routes/assurance-deces'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiLeadRouteImport } from './routes/api/lead'

const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifMutuelleSanteRoute = TarifMutuelleSanteRouteImport.update({
  id: '/tarif-mutuelle-sante',
  path: '/tarif-mutuelle-sante',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrixMutuelleSanteRoute = PrixMutuelleSanteRouteImport.update({
  id: '/prix-mutuelle-sante',
  path: '/prix-mutuelle-sante',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MutuelleSeniorPasCherRoute = MutuelleSeniorPasCherRouteImport.update({
  id: '/mutuelle-senior-pas-cher',
  path: '/mutuelle-senior-pas-cher',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSenior70AnsRoute = MutuelleSenior70AnsRouteImport.update({
  id: '/mutuelle-senior-70-ans',
  path: '/mutuelle-senior-70-ans',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSanteToulouseRoute = MutuelleSanteToulouseRouteImport.update({
  id: '/mutuelle-sante-toulouse',
  path: '/mutuelle-sante-toulouse',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSanteSansDelaiCarenceRoute =
  MutuelleSanteSansDelaiCarenceRouteImport.update({
    id: '/mutuelle-sante-sans-delai-carence',
    path: '/mutuelle-sante-sans-delai-carence',
    getParentRoute: () => rootRouteImport,
  } as any)
const MutuelleSantePasChereRoute = MutuelleSantePasChereRouteImport.update({
  id: '/mutuelle-sante-pas-chere',
  path: '/mutuelle-sante-pas-chere',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSanteParisRoute = MutuelleSanteParisRouteImport.update({
  id: '/mutuelle-sante-paris',
  path: '/mutuelle-sante-paris',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSanteMarseilleRoute = MutuelleSanteMarseilleRouteImport.update({
  id: '/mutuelle-sante-marseille',
  path: '/mutuelle-sante-marseille',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSanteLyonRoute = MutuelleSanteLyonRouteImport.update({
  id: '/mutuelle-sante-lyon',
  path: '/mutuelle-sante-lyon',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSanteIndependantRoute =
  MutuelleSanteIndependantRouteImport.update({
    id: '/mutuelle-sante-independant',
    path: '/mutuelle-sante-independant',
    getParentRoute: () => rootRouteImport,
  } as any)
const MutuelleSanteFonctionnaireRoute =
  MutuelleSanteFonctionnaireRouteImport.update({
    id: '/mutuelle-sante-fonctionnaire',
    path: '/mutuelle-sante-fonctionnaire',
    getParentRoute: () => rootRouteImport,
  } as any)
const MutuelleSanteFamilleRoute = MutuelleSanteFamilleRouteImport.update({
  id: '/mutuelle-sante-famille',
  path: '/mutuelle-sante-famille',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSanteExpatrieRoute = MutuelleSanteExpatrieRouteImport.update({
  id: '/mutuelle-sante-expatrie',
  path: '/mutuelle-sante-expatrie',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSanteEtudiantRoute = MutuelleSanteEtudiantRouteImport.update({
  id: '/mutuelle-sante-etudiant',
  path: '/mutuelle-sante-etudiant',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSanteEntrepriseRoute = MutuelleSanteEntrepriseRouteImport.update({
  id: '/mutuelle-sante-entreprise',
  path: '/mutuelle-sante-entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSanteEnLigneRoute = MutuelleSanteEnLigneRouteImport.update({
  id: '/mutuelle-sante-en-ligne',
  path: '/mutuelle-sante-en-ligne',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSanteBordeauxRoute = MutuelleSanteBordeauxRouteImport.update({
  id: '/mutuelle-sante-bordeaux',
  path: '/mutuelle-sante-bordeaux',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleSanteRoute = MutuelleSanteRouteImport.update({
  id: '/mutuelle-sante',
  path: '/mutuelle-sante',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleOptiqueRoute = MutuelleOptiqueRouteImport.update({
  id: '/mutuelle-optique',
  path: '/mutuelle-optique',
  getParentRoute: () => rootRouteImport,
} as any)
const MutuelleDentaireRoute = MutuelleDentaireRouteImport.update({
  id: '/mutuelle-dentaire',
  path: '/mutuelle-dentaire',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MeilleureMutuelleSanteRoute = MeilleureMutuelleSanteRouteImport.update({
  id: '/meilleure-mutuelle-sante',
  path: '/meilleure-mutuelle-sante',
  getParentRoute: () => rootRouteImport,
} as any)
const LoiLemoineRoute = LoiLemoineRouteImport.update({
  id: '/loi-lemoine',
  path: '/loi-lemoine',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisMutuelleSanteRoute = DevisMutuelleSanteRouteImport.update({
  id: '/devis-mutuelle-sante',
  path: '/devis-mutuelle-sante',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratObsequesRoute = ContratObsequesRouteImport.update({
  id: '/contrat-obseques',
  path: '/contrat-obseques',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplementaireSanteRoute = ComplementaireSanteRouteImport.update({
  id: '/complementaire-sante',
  path: '/complementaire-sante',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparateurMutuelleSeniorRoute =
  ComparateurMutuelleSeniorRouteImport.update({
    id: '/comparateur-mutuelle-senior',
    path: '/comparateur-mutuelle-senior',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComparateurMutuelleSanteRoute =
  ComparateurMutuelleSanteRouteImport.update({
    id: '/comparateur-mutuelle-sante',
    path: '/comparateur-mutuelle-sante',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChangerAssuranceEmprunteurRoute =
  ChangerAssuranceEmprunteurRouteImport.update({
    id: '/changer-assurance-emprunteur',
    path: '/changer-assurance-emprunteur',
    getParentRoute: () => rootRouteImport,
  } as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceObsequesRoute = AssuranceObsequesRouteImport.update({
  id: '/assurance-obseques',
  path: '/assurance-obseques',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceHospitalisationRoute =
  AssuranceHospitalisationRouteImport.update({
    id: '/assurance-hospitalisation',
    path: '/assurance-hospitalisation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssuranceEmprunteurRoute = AssuranceEmprunteurRouteImport.update({
  id: '/assurance-emprunteur',
  path: '/assurance-emprunteur',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceDecesRoute = AssuranceDecesRouteImport.update({
  id: '/assurance-deces',
  path: '/assurance-deces',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assurance-deces': typeof AssuranceDecesRoute
  '/assurance-emprunteur': typeof AssuranceEmprunteurRoute
  '/assurance-hospitalisation': typeof AssuranceHospitalisationRoute
  '/assurance-obseques': typeof AssuranceObsequesRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgu': typeof CguRoute
  '/changer-assurance-emprunteur': typeof ChangerAssuranceEmprunteurRoute
  '/comparateur-mutuelle-sante': typeof ComparateurMutuelleSanteRoute
  '/comparateur-mutuelle-senior': typeof ComparateurMutuelleSeniorRoute
  '/complementaire-sante': typeof ComplementaireSanteRoute
  '/contrat-obseques': typeof ContratObsequesRoute
  '/devis-mutuelle-sante': typeof DevisMutuelleSanteRoute
  '/leads': typeof LeadsRoute
  '/loi-lemoine': typeof LoiLemoineRoute
  '/meilleure-mutuelle-sante': typeof MeilleureMutuelleSanteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mutuelle-dentaire': typeof MutuelleDentaireRoute
  '/mutuelle-optique': typeof MutuelleOptiqueRoute
  '/mutuelle-sante': typeof MutuelleSanteRoute
  '/mutuelle-sante-bordeaux': typeof MutuelleSanteBordeauxRoute
  '/mutuelle-sante-en-ligne': typeof MutuelleSanteEnLigneRoute
  '/mutuelle-sante-entreprise': typeof MutuelleSanteEntrepriseRoute
  '/mutuelle-sante-etudiant': typeof MutuelleSanteEtudiantRoute
  '/mutuelle-sante-expatrie': typeof MutuelleSanteExpatrieRoute
  '/mutuelle-sante-famille': typeof MutuelleSanteFamilleRoute
  '/mutuelle-sante-fonctionnaire': typeof MutuelleSanteFonctionnaireRoute
  '/mutuelle-sante-independant': typeof MutuelleSanteIndependantRoute
  '/mutuelle-sante-lyon': typeof MutuelleSanteLyonRoute
  '/mutuelle-sante-marseille': typeof MutuelleSanteMarseilleRoute
  '/mutuelle-sante-paris': typeof MutuelleSanteParisRoute
  '/mutuelle-sante-pas-chere': typeof MutuelleSantePasChereRoute
  '/mutuelle-sante-sans-delai-carence': typeof MutuelleSanteSansDelaiCarenceRoute
  '/mutuelle-sante-toulouse': typeof MutuelleSanteToulouseRoute
  '/mutuelle-senior-70-ans': typeof MutuelleSenior70AnsRoute
  '/mutuelle-senior-pas-cher': typeof MutuelleSeniorPasCherRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/prix-mutuelle-sante': typeof PrixMutuelleSanteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarif-mutuelle-sante': typeof TarifMutuelleSanteRoute
  '/visitors': typeof VisitorsRoute
  '/api/lead': typeof ApiLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assurance-deces': typeof AssuranceDecesRoute
  '/assurance-emprunteur': typeof AssuranceEmprunteurRoute
  '/assurance-hospitalisation': typeof AssuranceHospitalisationRoute
  '/assurance-obseques': typeof AssuranceObsequesRoute
  '/cgu': typeof CguRoute
  '/changer-assurance-emprunteur': typeof ChangerAssuranceEmprunteurRoute
  '/comparateur-mutuelle-sante': typeof ComparateurMutuelleSanteRoute
  '/comparateur-mutuelle-senior': typeof ComparateurMutuelleSeniorRoute
  '/complementaire-sante': typeof ComplementaireSanteRoute
  '/contrat-obseques': typeof ContratObsequesRoute
  '/devis-mutuelle-sante': typeof DevisMutuelleSanteRoute
  '/leads': typeof LeadsRoute
  '/loi-lemoine': typeof LoiLemoineRoute
  '/meilleure-mutuelle-sante': typeof MeilleureMutuelleSanteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mutuelle-dentaire': typeof MutuelleDentaireRoute
  '/mutuelle-optique': typeof MutuelleOptiqueRoute
  '/mutuelle-sante': typeof MutuelleSanteRoute
  '/mutuelle-sante-bordeaux': typeof MutuelleSanteBordeauxRoute
  '/mutuelle-sante-en-ligne': typeof MutuelleSanteEnLigneRoute
  '/mutuelle-sante-entreprise': typeof MutuelleSanteEntrepriseRoute
  '/mutuelle-sante-etudiant': typeof MutuelleSanteEtudiantRoute
  '/mutuelle-sante-expatrie': typeof MutuelleSanteExpatrieRoute
  '/mutuelle-sante-famille': typeof MutuelleSanteFamilleRoute
  '/mutuelle-sante-fonctionnaire': typeof MutuelleSanteFonctionnaireRoute
  '/mutuelle-sante-independant': typeof MutuelleSanteIndependantRoute
  '/mutuelle-sante-lyon': typeof MutuelleSanteLyonRoute
  '/mutuelle-sante-marseille': typeof MutuelleSanteMarseilleRoute
  '/mutuelle-sante-paris': typeof MutuelleSanteParisRoute
  '/mutuelle-sante-pas-chere': typeof MutuelleSantePasChereRoute
  '/mutuelle-sante-sans-delai-carence': typeof MutuelleSanteSansDelaiCarenceRoute
  '/mutuelle-sante-toulouse': typeof MutuelleSanteToulouseRoute
  '/mutuelle-senior-70-ans': typeof MutuelleSenior70AnsRoute
  '/mutuelle-senior-pas-cher': typeof MutuelleSeniorPasCherRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/prix-mutuelle-sante': typeof PrixMutuelleSanteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarif-mutuelle-sante': typeof TarifMutuelleSanteRoute
  '/visitors': typeof VisitorsRoute
  '/api/lead': typeof ApiLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assurance-deces': typeof AssuranceDecesRoute
  '/assurance-emprunteur': typeof AssuranceEmprunteurRoute
  '/assurance-hospitalisation': typeof AssuranceHospitalisationRoute
  '/assurance-obseques': typeof AssuranceObsequesRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgu': typeof CguRoute
  '/changer-assurance-emprunteur': typeof ChangerAssuranceEmprunteurRoute
  '/comparateur-mutuelle-sante': typeof ComparateurMutuelleSanteRoute
  '/comparateur-mutuelle-senior': typeof ComparateurMutuelleSeniorRoute
  '/complementaire-sante': typeof ComplementaireSanteRoute
  '/contrat-obseques': typeof ContratObsequesRoute
  '/devis-mutuelle-sante': typeof DevisMutuelleSanteRoute
  '/leads': typeof LeadsRoute
  '/loi-lemoine': typeof LoiLemoineRoute
  '/meilleure-mutuelle-sante': typeof MeilleureMutuelleSanteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mutuelle-dentaire': typeof MutuelleDentaireRoute
  '/mutuelle-optique': typeof MutuelleOptiqueRoute
  '/mutuelle-sante': typeof MutuelleSanteRoute
  '/mutuelle-sante-bordeaux': typeof MutuelleSanteBordeauxRoute
  '/mutuelle-sante-en-ligne': typeof MutuelleSanteEnLigneRoute
  '/mutuelle-sante-entreprise': typeof MutuelleSanteEntrepriseRoute
  '/mutuelle-sante-etudiant': typeof MutuelleSanteEtudiantRoute
  '/mutuelle-sante-expatrie': typeof MutuelleSanteExpatrieRoute
  '/mutuelle-sante-famille': typeof MutuelleSanteFamilleRoute
  '/mutuelle-sante-fonctionnaire': typeof MutuelleSanteFonctionnaireRoute
  '/mutuelle-sante-independant': typeof MutuelleSanteIndependantRoute
  '/mutuelle-sante-lyon': typeof MutuelleSanteLyonRoute
  '/mutuelle-sante-marseille': typeof MutuelleSanteMarseilleRoute
  '/mutuelle-sante-paris': typeof MutuelleSanteParisRoute
  '/mutuelle-sante-pas-chere': typeof MutuelleSantePasChereRoute
  '/mutuelle-sante-sans-delai-carence': typeof MutuelleSanteSansDelaiCarenceRoute
  '/mutuelle-sante-toulouse': typeof MutuelleSanteToulouseRoute
  '/mutuelle-senior-70-ans': typeof MutuelleSenior70AnsRoute
  '/mutuelle-senior-pas-cher': typeof MutuelleSeniorPasCherRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/prix-mutuelle-sante': typeof PrixMutuelleSanteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarif-mutuelle-sante': typeof TarifMutuelleSanteRoute
  '/visitors': typeof VisitorsRoute
  '/api/lead': typeof ApiLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assurance-deces'
    | '/assurance-emprunteur'
    | '/assurance-hospitalisation'
    | '/assurance-obseques'
    | '/blog'
    | '/cgu'
    | '/changer-assurance-emprunteur'
    | '/comparateur-mutuelle-sante'
    | '/comparateur-mutuelle-senior'
    | '/complementaire-sante'
    | '/contrat-obseques'
    | '/devis-mutuelle-sante'
    | '/leads'
    | '/loi-lemoine'
    | '/meilleure-mutuelle-sante'
    | '/mentions-legales'
    | '/mutuelle-dentaire'
    | '/mutuelle-optique'
    | '/mutuelle-sante'
    | '/mutuelle-sante-bordeaux'
    | '/mutuelle-sante-en-ligne'
    | '/mutuelle-sante-entreprise'
    | '/mutuelle-sante-etudiant'
    | '/mutuelle-sante-expatrie'
    | '/mutuelle-sante-famille'
    | '/mutuelle-sante-fonctionnaire'
    | '/mutuelle-sante-independant'
    | '/mutuelle-sante-lyon'
    | '/mutuelle-sante-marseille'
    | '/mutuelle-sante-paris'
    | '/mutuelle-sante-pas-chere'
    | '/mutuelle-sante-sans-delai-carence'
    | '/mutuelle-sante-toulouse'
    | '/mutuelle-senior-70-ans'
    | '/mutuelle-senior-pas-cher'
    | '/politique-de-confidentialite'
    | '/prix-mutuelle-sante'
    | '/sitemap.xml'
    | '/tarif-mutuelle-sante'
    | '/visitors'
    | '/api/lead'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assurance-deces'
    | '/assurance-emprunteur'
    | '/assurance-hospitalisation'
    | '/assurance-obseques'
    | '/cgu'
    | '/changer-assurance-emprunteur'
    | '/comparateur-mutuelle-sante'
    | '/comparateur-mutuelle-senior'
    | '/complementaire-sante'
    | '/contrat-obseques'
    | '/devis-mutuelle-sante'
    | '/leads'
    | '/loi-lemoine'
    | '/meilleure-mutuelle-sante'
    | '/mentions-legales'
    | '/mutuelle-dentaire'
    | '/mutuelle-optique'
    | '/mutuelle-sante'
    | '/mutuelle-sante-bordeaux'
    | '/mutuelle-sante-en-ligne'
    | '/mutuelle-sante-entreprise'
    | '/mutuelle-sante-etudiant'
    | '/mutuelle-sante-expatrie'
    | '/mutuelle-sante-famille'
    | '/mutuelle-sante-fonctionnaire'
    | '/mutuelle-sante-independant'
    | '/mutuelle-sante-lyon'
    | '/mutuelle-sante-marseille'
    | '/mutuelle-sante-paris'
    | '/mutuelle-sante-pas-chere'
    | '/mutuelle-sante-sans-delai-carence'
    | '/mutuelle-sante-toulouse'
    | '/mutuelle-senior-70-ans'
    | '/mutuelle-senior-pas-cher'
    | '/politique-de-confidentialite'
    | '/prix-mutuelle-sante'
    | '/sitemap.xml'
    | '/tarif-mutuelle-sante'
    | '/visitors'
    | '/api/lead'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/assurance-deces'
    | '/assurance-emprunteur'
    | '/assurance-hospitalisation'
    | '/assurance-obseques'
    | '/blog'
    | '/cgu'
    | '/changer-assurance-emprunteur'
    | '/comparateur-mutuelle-sante'
    | '/comparateur-mutuelle-senior'
    | '/complementaire-sante'
    | '/contrat-obseques'
    | '/devis-mutuelle-sante'
    | '/leads'
    | '/loi-lemoine'
    | '/meilleure-mutuelle-sante'
    | '/mentions-legales'
    | '/mutuelle-dentaire'
    | '/mutuelle-optique'
    | '/mutuelle-sante'
    | '/mutuelle-sante-bordeaux'
    | '/mutuelle-sante-en-ligne'
    | '/mutuelle-sante-entreprise'
    | '/mutuelle-sante-etudiant'
    | '/mutuelle-sante-expatrie'
    | '/mutuelle-sante-famille'
    | '/mutuelle-sante-fonctionnaire'
    | '/mutuelle-sante-independant'
    | '/mutuelle-sante-lyon'
    | '/mutuelle-sante-marseille'
    | '/mutuelle-sante-paris'
    | '/mutuelle-sante-pas-chere'
    | '/mutuelle-sante-sans-delai-carence'
    | '/mutuelle-sante-toulouse'
    | '/mutuelle-senior-70-ans'
    | '/mutuelle-senior-pas-cher'
    | '/politique-de-confidentialite'
    | '/prix-mutuelle-sante'
    | '/sitemap.xml'
    | '/tarif-mutuelle-sante'
    | '/visitors'
    | '/api/lead'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssuranceDecesRoute: typeof AssuranceDecesRoute
  AssuranceEmprunteurRoute: typeof AssuranceEmprunteurRoute
  AssuranceHospitalisationRoute: typeof AssuranceHospitalisationRoute
  AssuranceObsequesRoute: typeof AssuranceObsequesRoute
  BlogRoute: typeof BlogRouteWithChildren
  CguRoute: typeof CguRoute
  ChangerAssuranceEmprunteurRoute: typeof ChangerAssuranceEmprunteurRoute
  ComparateurMutuelleSanteRoute: typeof ComparateurMutuelleSanteRoute
  ComparateurMutuelleSeniorRoute: typeof ComparateurMutuelleSeniorRoute
  ComplementaireSanteRoute: typeof ComplementaireSanteRoute
  ContratObsequesRoute: typeof ContratObsequesRoute
  DevisMutuelleSanteRoute: typeof DevisMutuelleSanteRoute
  LeadsRoute: typeof LeadsRoute
  LoiLemoineRoute: typeof LoiLemoineRoute
  MeilleureMutuelleSanteRoute: typeof MeilleureMutuelleSanteRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MutuelleDentaireRoute: typeof MutuelleDentaireRoute
  MutuelleOptiqueRoute: typeof MutuelleOptiqueRoute
  MutuelleSanteRoute: typeof MutuelleSanteRoute
  MutuelleSanteBordeauxRoute: typeof MutuelleSanteBordeauxRoute
  MutuelleSanteEnLigneRoute: typeof MutuelleSanteEnLigneRoute
  MutuelleSanteEntrepriseRoute: typeof MutuelleSanteEntrepriseRoute
  MutuelleSanteEtudiantRoute: typeof MutuelleSanteEtudiantRoute
  MutuelleSanteExpatrieRoute: typeof MutuelleSanteExpatrieRoute
  MutuelleSanteFamilleRoute: typeof MutuelleSanteFamilleRoute
  MutuelleSanteFonctionnaireRoute: typeof MutuelleSanteFonctionnaireRoute
  MutuelleSanteIndependantRoute: typeof MutuelleSanteIndependantRoute
  MutuelleSanteLyonRoute: typeof MutuelleSanteLyonRoute
  MutuelleSanteMarseilleRoute: typeof MutuelleSanteMarseilleRoute
  MutuelleSanteParisRoute: typeof MutuelleSanteParisRoute
  MutuelleSantePasChereRoute: typeof MutuelleSantePasChereRoute
  MutuelleSanteSansDelaiCarenceRoute: typeof MutuelleSanteSansDelaiCarenceRoute
  MutuelleSanteToulouseRoute: typeof MutuelleSanteToulouseRoute
  MutuelleSenior70AnsRoute: typeof MutuelleSenior70AnsRoute
  MutuelleSeniorPasCherRoute: typeof MutuelleSeniorPasCherRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  PrixMutuelleSanteRoute: typeof PrixMutuelleSanteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifMutuelleSanteRoute: typeof TarifMutuelleSanteRoute
  VisitorsRoute: typeof VisitorsRoute
  ApiLeadRoute: typeof ApiLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarif-mutuelle-sante': {
      id: '/tarif-mutuelle-sante'
      path: '/tarif-mutuelle-sante'
      fullPath: '/tarif-mutuelle-sante'
      preLoaderRoute: typeof TarifMutuelleSanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prix-mutuelle-sante': {
      id: '/prix-mutuelle-sante'
      path: '/prix-mutuelle-sante'
      fullPath: '/prix-mutuelle-sante'
      preLoaderRoute: typeof PrixMutuelleSanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-senior-pas-cher': {
      id: '/mutuelle-senior-pas-cher'
      path: '/mutuelle-senior-pas-cher'
      fullPath: '/mutuelle-senior-pas-cher'
      preLoaderRoute: typeof MutuelleSeniorPasCherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-senior-70-ans': {
      id: '/mutuelle-senior-70-ans'
      path: '/mutuelle-senior-70-ans'
      fullPath: '/mutuelle-senior-70-ans'
      preLoaderRoute: typeof MutuelleSenior70AnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-toulouse': {
      id: '/mutuelle-sante-toulouse'
      path: '/mutuelle-sante-toulouse'
      fullPath: '/mutuelle-sante-toulouse'
      preLoaderRoute: typeof MutuelleSanteToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-sans-delai-carence': {
      id: '/mutuelle-sante-sans-delai-carence'
      path: '/mutuelle-sante-sans-delai-carence'
      fullPath: '/mutuelle-sante-sans-delai-carence'
      preLoaderRoute: typeof MutuelleSanteSansDelaiCarenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-pas-chere': {
      id: '/mutuelle-sante-pas-chere'
      path: '/mutuelle-sante-pas-chere'
      fullPath: '/mutuelle-sante-pas-chere'
      preLoaderRoute: typeof MutuelleSantePasChereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-paris': {
      id: '/mutuelle-sante-paris'
      path: '/mutuelle-sante-paris'
      fullPath: '/mutuelle-sante-paris'
      preLoaderRoute: typeof MutuelleSanteParisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-marseille': {
      id: '/mutuelle-sante-marseille'
      path: '/mutuelle-sante-marseille'
      fullPath: '/mutuelle-sante-marseille'
      preLoaderRoute: typeof MutuelleSanteMarseilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-lyon': {
      id: '/mutuelle-sante-lyon'
      path: '/mutuelle-sante-lyon'
      fullPath: '/mutuelle-sante-lyon'
      preLoaderRoute: typeof MutuelleSanteLyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-independant': {
      id: '/mutuelle-sante-independant'
      path: '/mutuelle-sante-independant'
      fullPath: '/mutuelle-sante-independant'
      preLoaderRoute: typeof MutuelleSanteIndependantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-fonctionnaire': {
      id: '/mutuelle-sante-fonctionnaire'
      path: '/mutuelle-sante-fonctionnaire'
      fullPath: '/mutuelle-sante-fonctionnaire'
      preLoaderRoute: typeof MutuelleSanteFonctionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-famille': {
      id: '/mutuelle-sante-famille'
      path: '/mutuelle-sante-famille'
      fullPath: '/mutuelle-sante-famille'
      preLoaderRoute: typeof MutuelleSanteFamilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-expatrie': {
      id: '/mutuelle-sante-expatrie'
      path: '/mutuelle-sante-expatrie'
      fullPath: '/mutuelle-sante-expatrie'
      preLoaderRoute: typeof MutuelleSanteExpatrieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-etudiant': {
      id: '/mutuelle-sante-etudiant'
      path: '/mutuelle-sante-etudiant'
      fullPath: '/mutuelle-sante-etudiant'
      preLoaderRoute: typeof MutuelleSanteEtudiantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-entreprise': {
      id: '/mutuelle-sante-entreprise'
      path: '/mutuelle-sante-entreprise'
      fullPath: '/mutuelle-sante-entreprise'
      preLoaderRoute: typeof MutuelleSanteEntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-en-ligne': {
      id: '/mutuelle-sante-en-ligne'
      path: '/mutuelle-sante-en-ligne'
      fullPath: '/mutuelle-sante-en-ligne'
      preLoaderRoute: typeof MutuelleSanteEnLigneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante-bordeaux': {
      id: '/mutuelle-sante-bordeaux'
      path: '/mutuelle-sante-bordeaux'
      fullPath: '/mutuelle-sante-bordeaux'
      preLoaderRoute: typeof MutuelleSanteBordeauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-sante': {
      id: '/mutuelle-sante'
      path: '/mutuelle-sante'
      fullPath: '/mutuelle-sante'
      preLoaderRoute: typeof MutuelleSanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-optique': {
      id: '/mutuelle-optique'
      path: '/mutuelle-optique'
      fullPath: '/mutuelle-optique'
      preLoaderRoute: typeof MutuelleOptiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutuelle-dentaire': {
      id: '/mutuelle-dentaire'
      path: '/mutuelle-dentaire'
      fullPath: '/mutuelle-dentaire'
      preLoaderRoute: typeof MutuelleDentaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meilleure-mutuelle-sante': {
      id: '/meilleure-mutuelle-sante'
      path: '/meilleure-mutuelle-sante'
      fullPath: '/meilleure-mutuelle-sante'
      preLoaderRoute: typeof MeilleureMutuelleSanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loi-lemoine': {
      id: '/loi-lemoine'
      path: '/loi-lemoine'
      fullPath: '/loi-lemoine'
      preLoaderRoute: typeof LoiLemoineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis-mutuelle-sante': {
      id: '/devis-mutuelle-sante'
      path: '/devis-mutuelle-sante'
      fullPath: '/devis-mutuelle-sante'
      preLoaderRoute: typeof DevisMutuelleSanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrat-obseques': {
      id: '/contrat-obseques'
      path: '/contrat-obseques'
      fullPath: '/contrat-obseques'
      preLoaderRoute: typeof ContratObsequesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complementaire-sante': {
      id: '/complementaire-sante'
      path: '/complementaire-sante'
      fullPath: '/complementaire-sante'
      preLoaderRoute: typeof ComplementaireSanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparateur-mutuelle-senior': {
      id: '/comparateur-mutuelle-senior'
      path: '/comparateur-mutuelle-senior'
      fullPath: '/comparateur-mutuelle-senior'
      preLoaderRoute: typeof ComparateurMutuelleSeniorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparateur-mutuelle-sante': {
      id: '/comparateur-mutuelle-sante'
      path: '/comparateur-mutuelle-sante'
      fullPath: '/comparateur-mutuelle-sante'
      preLoaderRoute: typeof ComparateurMutuelleSanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changer-assurance-emprunteur': {
      id: '/changer-assurance-emprunteur'
      path: '/changer-assurance-emprunteur'
      fullPath: '/changer-assurance-emprunteur'
      preLoaderRoute: typeof ChangerAssuranceEmprunteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-obseques': {
      id: '/assurance-obseques'
      path: '/assurance-obseques'
      fullPath: '/assurance-obseques'
      preLoaderRoute: typeof AssuranceObsequesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-hospitalisation': {
      id: '/assurance-hospitalisation'
      path: '/assurance-hospitalisation'
      fullPath: '/assurance-hospitalisation'
      preLoaderRoute: typeof AssuranceHospitalisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-emprunteur': {
      id: '/assurance-emprunteur'
      path: '/assurance-emprunteur'
      fullPath: '/assurance-emprunteur'
      preLoaderRoute: typeof AssuranceEmprunteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-deces': {
      id: '/assurance-deces'
      path: '/assurance-deces'
      fullPath: '/assurance-deces'
      preLoaderRoute: typeof AssuranceDecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssuranceDecesRoute: AssuranceDecesRoute,
  AssuranceEmprunteurRoute: AssuranceEmprunteurRoute,
  AssuranceHospitalisationRoute: AssuranceHospitalisationRoute,
  AssuranceObsequesRoute: AssuranceObsequesRoute,
  BlogRoute: BlogRouteWithChildren,
  CguRoute: CguRoute,
  ChangerAssuranceEmprunteurRoute: ChangerAssuranceEmprunteurRoute,
  ComparateurMutuelleSanteRoute: ComparateurMutuelleSanteRoute,
  ComparateurMutuelleSeniorRoute: ComparateurMutuelleSeniorRoute,
  ComplementaireSanteRoute: ComplementaireSanteRoute,
  ContratObsequesRoute: ContratObsequesRoute,
  DevisMutuelleSanteRoute: DevisMutuelleSanteRoute,
  LeadsRoute: LeadsRoute,
  LoiLemoineRoute: LoiLemoineRoute,
  MeilleureMutuelleSanteRoute: MeilleureMutuelleSanteRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MutuelleDentaireRoute: MutuelleDentaireRoute,
  MutuelleOptiqueRoute: MutuelleOptiqueRoute,
  MutuelleSanteRoute: MutuelleSanteRoute,
  MutuelleSanteBordeauxRoute: MutuelleSanteBordeauxRoute,
  MutuelleSanteEnLigneRoute: MutuelleSanteEnLigneRoute,
  MutuelleSanteEntrepriseRoute: MutuelleSanteEntrepriseRoute,
  MutuelleSanteEtudiantRoute: MutuelleSanteEtudiantRoute,
  MutuelleSanteExpatrieRoute: MutuelleSanteExpatrieRoute,
  MutuelleSanteFamilleRoute: MutuelleSanteFamilleRoute,
  MutuelleSanteFonctionnaireRoute: MutuelleSanteFonctionnaireRoute,
  MutuelleSanteIndependantRoute: MutuelleSanteIndependantRoute,
  MutuelleSanteLyonRoute: MutuelleSanteLyonRoute,
  MutuelleSanteMarseilleRoute: MutuelleSanteMarseilleRoute,
  MutuelleSanteParisRoute: MutuelleSanteParisRoute,
  MutuelleSantePasChereRoute: MutuelleSantePasChereRoute,
  MutuelleSanteSansDelaiCarenceRoute: MutuelleSanteSansDelaiCarenceRoute,
  MutuelleSanteToulouseRoute: MutuelleSanteToulouseRoute,
  MutuelleSenior70AnsRoute: MutuelleSenior70AnsRoute,
  MutuelleSeniorPasCherRoute: MutuelleSeniorPasCherRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  PrixMutuelleSanteRoute: PrixMutuelleSanteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifMutuelleSanteRoute: TarifMutuelleSanteRoute,
  VisitorsRoute: VisitorsRoute,
  ApiLeadRoute: ApiLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
